require 'pry'
require 'httparty'
require 'date'
require 'nokogiri'
require 'open-uri'
require 'open_uri_redirections'
#tried to show new tab for image-url but didn't know how, maybe I can ask on wed
#require 'selenium-webdriver'

require 'launchy'
require_relative '../lib/marvel_characters.rb'
require_relative '../lib/cli.rb'
require_relative '../lib/api.rb'
require_relative '../lib/marvelbattle.rb'
require_relative '../lib/human.rb'
require_relative '../lib/computer.rb'